### ISSUE TITLE
浮动与定位

### ISSUE THREAD

**Issue by Zoe-IQ** [Zoe-IQ/FE#5]
# 一、浮动

1、正常情况下`div1` `div2` `div3` 依次上下排列
![image](https://user-images.githubusercontent.com/43318424/126032675-4541b3e8-91c9-4bd7-9b2d-9b7112639104.png)

```html
// html

<div>
    <div class="div1">div1</div>
    <div class="div2">div2</div>
    <div class="div3">div3</div>
</div>
```

```css
// css

.div1 {
    background-color: skyblue;
    width: 100px;
    height: 100px;
}
.div2 {
    width: 200px;
    height: 200px;
    background-color: yellow;
}
.div3 {
    width: 200px;
    height: 200px;
    background-color: green;
}
````

2、将 `div1` 设置为向左浮动 ，可以发现浮动的 `div1` 脱离文档流，浮动在 `div2` 上层，因为下层的 `div2` 会占据 `div1` 脱离的位置

![image](https://user-images.githubusercontent.com/43318424/126032709-672c7053-49ca-4799-ae9b-cb2dafc7ad43.png)

````css
.div1 {
    background-color: skyblue;
    float: left;  // 设置左浮动
    width: 100px;
    height: 100px;
}
.div2 {
    width: 200px;
    height: 200px;
    background-color: yellow;
}
.div3 {
    width: 200px;
    height: 200px;
    background-color: green;
}
````

3、`div2` 设置清除浮动，可以发现 `div2` 设置清除左浮动，会另起一行。可以理解为 `div2` 左边不允许出现浮动元素，将会换行，不出现在 `div1` 同一行
![image](https://user-images.githubusercontent.com/43318424/126032763-9ae8856f-f2d7-4bb8-a56e-c602c2b522ef.png)
````css
.div1 {
    background-color: skyblue;
    float: left;
    width: 100px;
    height: 100px;
}
.div2 {
    width: 200px;
    height: 200px;
    background-color: yellow;
    clear: left;
}
.div3 {
    width: 200px;
    height: 200px;
    background-color: green;
}
````

### 浮动的特点：
1. 让块级元素在一行显式
2. 使行内元素具有块级元素特征
3. 浮动元素不设置宽高时，宽、高由内容撑开
4. 浮动后的子元素无法撑开父元素（高度塌陷）
5. 浮动元素**在当前行**向指定的方向浮动，直到他的外边缘碰到**父元素边框**或者**浮动框的边框**为止
6. 浮动元素会**脱离文档流**，提升层级，后面的元素将会顶上去，占据浮动元素的原本位置

### 清除浮动
- clear:left 不允许当前元素所在行的左侧有浮动元素，如果有，当前元素会换行
- clear:right 不允许当前元素所在行的右侧有浮动元素，如果有，当前元素会换行
- clear:both 不允许当前元素所在行的左右有浮动元素，如果有，当前元素会换行

# 二、定位

### 1、静态定位

````css
{
	position：static
}
````
无定位，元素正常出现

### 2、相对定位
````css
{
	position：relative
}
````
1. 只设置相对定位，不设置偏移量，定位后的元素和定位之前位置没变化
2. 元素定位后不会脱离文档流（**原来的位置依然占着空间**）
3. 相对定位会提升层级（**偏移后会覆盖其他元素**）
4. 相对定位根据自身的原始位置计算位移位置

#### 示例：
正常情况下，前三个div框展示成行内块，依次排列，最后一个div展示文字
![image](https://user-images.githubusercontent.com/43318424/126033080-40939382-bb81-4d79-b001-b34caf69f2c9.png)

```` html
<div class="son1">框1</div>
<div class="son2">框2</div>
<div class="son3">框3</div>
<div>testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest</div>
````

````css
.son1,
.son2,
.son3{
    width: 100px;
    height: 100px;
    margin: 5px;
    display: inline-block;
    border: 1px dashed black;
}

.son1{
    background: #0FF;
}
.son2{
    background: #9CF;
}

.son3{
    background: #F9F;
}
````

给第二个框添加相对定位，偏移左50px，偏离上30px，可以发现框2设置相对定位后，不会脱离文档流（原先的位置依然占据），而且提高了层级（遮住框3和文字）
![image](https://user-images.githubusercontent.com/43318424/126033132-6c6efe48-d1e3-41d9-9950-937554da9912.png)

````css
.son2{
    background: #9CF;
    position: relative;
    left: 50px;
    top: 30px;
}
````

### 3、绝对定位
````css
{
	position：absolute
}
````
给框2设置绝对定位后
![image](https://user-images.githubusercontent.com/43318424/126033277-580b7ad2-11ff-4d24-9e5b-8317f9ebfb5f.png)

1. 只设置绝对定位，不设置偏移量，元素还在原来位置，但是会脱离文档流（即不占原来的空间了）

2. 提升层级（框2压在框3上面）

3. 绝对定位相对于**最近的**、**有定位的**（不包括默认的static，只有relative、fixed）父元素偏移，如果所有祖先元素都没有定位，则根据最外层的包含边框的来计算自己的坐标（一般将父元素设为相对定位，父相子绝）

4. 绝对定位的元素**不设置宽度时，宽度由内容撑开**

5. 使行内元素变为块级元素

6. 触发BFC

### 4、固定定位
````css
{
	position：fixed
}
````
相对于浏览器可视窗口的定位，位置固定，不会随着网页滚动条的滚动而移动

1. 脱离文档流、提升层级（不占原来的空间）
2. 固定在浏览器可视区的某一个位置上
3. 根据浏览器的可视窗口计算偏移后位置
4. 使行内样式支持宽高、内外边距
5. 触发BFC

### 定位总结对比
|                            | 相对定位         | 绝对定位                                 | 固定定位                 |
| -------------------------- | ---------------- | ---------------------------------------- | ------------------------ |
| 脱离文档流                 | ×                | √                                        | √                        |
| 提升层级                   | √                | √                                        | √                        |
| 使行内元素具有块级元素特征 | ×                | √                                        | √                        |
| 触发BFC                    | ×                | √                                        | √                        |
| 新位置计算                 | 相对原来位置偏移 | 相对于**最近的**、**有定位的**父元素偏移 | 根据浏览器的可视窗口计算 |
